---
all:
  children:
    control_plane:
      hosts:
        cp1:
          ansible_host: 192.168.1.160
    workers:
      hosts:
        worker1:
          ansible_host: 192.168.1.161
        worker2:
          ansible_host: 192.168.1.162
        worker3:
          ansible_host: 192.168.1.169
    kube_cluster:
      children:
        control_plane:
        workers:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
