---
- name: Update apt cache (older than 1 hour)
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install baseline packages
  ansible.builtin.apt:
    name: "{{ common_base_packages }}"
    state: present

- name: Remove packages that conflict with Kubernetes
  ansible.builtin.apt:
    name:
      - ufw          # we'll use iptables/nftables directly
    state: absent